apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service
  database_name: auth-micro
  admin_mode: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: 
  mongo-root-username: {{REPLACE_HERE_MONGO_PASS}}
  mongo-root-password: {{REPLACE_HERE_MONGO_PASS}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-micro-mongo-statefulset
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.11
        env:
          - name: MONGO_INITDB_DATABASE
            valueFrom: 
              configMapKeyRef:
                name: mongodb-configmap
                key: database_name
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
        ports:
        - containerPort: 27017
          name: mongo-port
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017