apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-configmap
data:
  auth_url: "http://localhost:4003"
  manager_url: "http://localhost:4000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gui
  name: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - image: ghcr.io/ruggero95/api-manager/gui:master
        imagePullPolicy: Always
        name: gui
        env:
          - name: AUTH_URL
            valueFrom: 
              configMapKeyRef:
                name: gui-configmap
                key: auth_url
          - name: MANAGER_URL
            valueFrom: 
              configMapKeyRef:
                name: gui-configmap
                key: manager_url
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gui
  name: gui-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: gui
  # type: ClusterIP se uso ingress dopo
  type: LoadBalancer
